### ISSUE TITLE
Make-to-order

### ISSUE THREAD

**Issue by UB01382** [hdavid16/InventoryManagement.jl#78]
If there is a 0 lead time for a MTO product and a customer places an order for this material, it is currently not possible to fulfill it in the same time period. Currently a `service_lead_time` of at least 1 period is required.

This is because the `simulate_markets!` function only attempts to fulfill market demand with stock (not production). Thus, the stock will drop (negative) and a replenishment of that material will be requested in the next period. However, there is a potential issue: if a downstream node requests some of that material in the next time period, the material will be shipped downstream rather than being committed to the external customer.

**Comment by hdavid16** [comment]
#52ee197 closes issue with 0 lead time MTO (assuming a MTO is one for which there is zero stock and material is produced at that node)
